version: '3.8'

services:

  backend:
    restart: on-failure
    ports:
      - 5000:5000
    depends_on:
      - db
    build:
      context: backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    env_file:
      - secret.env
    environment:
      - DEFAULT_ADMIN_EMAIL=admin@gmail.com
      - DEFAULT_ADMIN_PASSWORD=admin123
      - DEFAULT_ADMIN_USERNAME=admin
      - PORT=5000
      - DATABASE_URL=postgres://app-db-user:app-db-password@db:5432/app-db
      - REFRESH_SECRET=somesecretrefreshtoken
      - SECRET=somesecretjwttoken
      - DROP_TABLES=false
    command: sh -c "air && go build main.go && ./main"
    networks:
      - app-net
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    image: frontend
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/app
    networks:
      - app-net
    # command: sh -c "rm -rf node_modules && npm install && npm start"
    command: sh -c "npm install && npm start"
