version: '3.8'

services:

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=app-db-password
      - POSTGRES_USER=app-db-user
      - POSTGRES_DB=app-db
    container_name: backend-db
    hostname: db
    networks:
      - app-net
    ports:
      - 5432:5432
    volumes:
      - backend-db:/var/lib/postgresql/data
  backend:
    restart: on-failure
    ports:
      - 5000:5000
    depends_on:
      - db
    build:
      context: backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    environment:
      - DEFAULT_ADMIN_USER=admin@gmail.com
      - DEFAULT_ADMIN_PASS=admin123
      - PORT=5000
      - DATABASE_URL=postgres://app-db-user:app-db-password@db:5432/app-db
      - SECRET=somesecretjwttoken
      - DROP_TABLES=true
    command: sh -c "air && go build main.go && ./main"
    networks:
      - app-net
  frontend:
    depends_on:
      - backend
    image: frontend
    ports:
      - 4200:4200
    volumes:
      - ./frontend/app:/app
    networks:
      - app-net

volumes:
  backend-db:


networks:
  app-net:
    driver: bridge
