version: '3.8'

services:

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=app-db-password
      - POSTGRES_USER=app-db-user
      - POSTGRES_DB=app-db
    container_name: backend-db
    hostname: db
    networks:
      - app-net
    ports:
      - 5432:5432
    volumes:
      - backend-db:/var/lib/postgresql/data

volumes:
  backend-db:


networks:
  app-net:
    driver: bridge
