version: '3.8'

services:

  backend:
    restart: on-failure
    ports:
      - 5000:5000
    depends_on:
      - db
    build:
      context: backend
      dockerfile: Dockerfile.prod
    volumes:
      - ./backend:/app
    environment:
      - DEFAULT_ADMIN_USER=admin@gmail.com
      - DEFAULT_ADMIN_PASS=admin123
      - PORT=5000
      - DATABASE_URL=postgres://app-db-user:app-db-password@db:5432/app-db
      - SECRET=somesecretjwttoken
      - DROP_TABLES=true
    networks:
      - app-net
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    image: frontend
    ports:
      - 4200:80
    volumes:
      - ./frontend:/app
    networks:
      - app-net
