FROM golang:1.18-alpine AS build

RUN apk add python3 tzdata
RUN go install github.com/cosmtrek/air@latest
WORKDIR /app/src

COPY src/email_service/*.py /email_service/
COPY src/email_service/requirements.txt /email_service/
WORKDIR /email_service
RUN python3 -m venv venv
RUN venv/bin/python -m pip install -r requirements.txt

ENV SITE_TIMESTAMP="verification_9d7d8a4_12/30/23 02:30:12"

WORKDIR /app/src