FROM golang:1.18-alpine AS build

RUN apk add python3 tzdata
RUN go install github.com/cosmtrek/air@latest
WORKDIR /app/src

COPY src/email_service/main.py /email_service/
COPY src/email_service/requirements.txt /email_service/
WORKDIR /email_service
RUN python3 -m venv venv
RUN venv/bin/python -m pip install -r requirements.txt

ENV SITE_TIMESTAMP="ids_8849620_12/28/23 01:03:52"

WORKDIR /app/src